server:
  port: 8080

spring:
  application:
    name: spring-security-project
  datasource:
    url: jdbc:mysql://auth-server.mysql.database.azure.com:3306/{authdb}?useSSL=true
    username: juandlr
    password: azure@1234
  jpa:
    show-sql: true 
    hibernate:
      ddl-auto: update
