server:
  port: 8080

spring:
  application:
    name: spring-security-project
  datasource:
    url: ${APPSETTING_DB_URL}
    username: ${APPSETTING_DB_USERNAME}
    password: ${APPSETTING_DB_PASSWORD}
  jpa:
    show-sql: true 
    hibernate:
      ddl-auto: update
