CREATE TABLE IF NOT EXISTS roles (
role_id BIGINT AUTO_INCREMENT PRIMARY KEY,
role_name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    role_id BIGINT,
    FOREIGN KEY (role_id) REFERENCES roles(role_id)
);